### ISSUE TITLE
Cái này dùng để làm gì vậy bro 

### ISSUE THREAD

**Issue by lequangnamsoraly2009** [trinhvanminh/SQL_Agent#1]
Cần được giải thích ?

**Comment by trinhvanminh** [comment]
Are you interested in this?

Nó như mấy con bot AI **text2SQL** á bạn

Nhưng cái này là nó có thêm
- Thông tin về schema
- Danh sách tables 
trong SQL của bạn nữa nên là nó chính xác hơn và kèm kết quả trả về của câu query đó luôn.

FYI: Như bạn thấy trong example thì có các bước trước đó, nếu bạn bấm vào thì sẽ thấy các bước để nó sinh ra câu SQL query tất nhiên là bao gồm cả câu query để có câu trả lời cuối.

**Comment by lequangnamsoraly2009** [comment]
Not interested about that :v 
but btw thanks for explain =))))))))))))))))))

**Comment by trinhvanminh** [comment]
ví dụ bro lười viết câu query thì dùng nó để gen câu query  :))

**Comment by lequangnamsoraly2009** [comment]
:v

**Comment by trinhvanminh** [comment]
totally free bro, no credit card required
